#SAHIL
S_user_name = "SK SAHIL UDDIN"
S_password = "sahil@2007"

#RANITa
R_user_name = "RANIT PAL"
R_password = "ranit@2007"

#AKASH
A_user_name = "AKASH BERA"
A_password = "akash@2006"

#ANKUR
An_user_name = "ANKUR BERA"
An_password = "ankur@2006"

#ZISAN
Z_user_name = "SK ZISAN ALI"
Z_password = "zisan@2006"



# TEST
in_user_name = input("Enter your user name in capital ")
in_password = input("Enter your password  ")


if in_user_name == S_user_name  or S_user_name + " " and in_password == S_password:
        print("Log in to ADMINISTRATOR")
        print("      ")
        print("      ")
        print("      ")
        print("Welcome BOOS ")
        print("      ")
        print("      ")
        print("      ")
        operator = int(input("(1).Details "))
        if operator == 1:
             print(" SK SAHIL UDDIN")
             print("      ")
             print("Your date of birth - 02/04/2007")
             print("      ")
             print("Your subjects is [English, Bengali, Physics, Chemistry, Math, Biology")
             print("      ")
             print("You are now class 12")
             print("      ")
             print("Your roll is 18")
             print("      ")
             print("      ")
             print("      ")
             print("Your pin code is 711412")
             print("      ")
             print("Your village - PURPAT ")
             print("      ")
             print("Your post - KANUPAT")
             print("      ")
             print("Your P.S - UDAYNARAYANPUR")
             print("      ")
             print("Your district - HOWRAH")
             print(" ")
             print(" ")
             print("THANK YOU FOR USING OUR SERVICES")
        else:
             print("invalid")

elif in_user_name == R_user_name or R_user_name + " "  and in_password == R_password:
     print("      ")
     print("      ")
     print("      ")
     print("      ")
     print("      ")
     print("      ")
     print("Log in into guest RANIT")
     print("      ")
     print("      ")
     print("      ")
     print("Welcome RANIT you are in our program ")
     print("      ")
     operator = int(input("(1).Details "))
     if operator == 1:
            print("RANIT PAL")
            print("      ")
            print("Your date of birth - 08/02/2007")
            print("      ")
            print("Your subjects is [English, Bengali, Physics, Chemistry, Math, Biology]")
            print("      ")
            print("You are now class 12")
            print("      ")
            print("Your roll is __")
            print("      ")
            print("      ")
            print("      ")
            print("Your pin code is ______")
            print("      ")
            print("Your village -  ")
            print("      ")
            print("Your post - ")
            print("      ")
            print("Your P.S - ")
            print("      ")
            print("Your district - HOWRAH")
            print(" ")
            print(" ")
            print("THANK YOU FOR USING OUR SERVICES")
            print(" Your wifi password is - ranit@2007")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
            print(" ")
     else:
        print("invalid")

elif in_user_name == A_user_name or A_user_name + " " and in_password == A_user_name:
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("Log in into guest AKASH")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("Welcome AKASH you are in our program ")
        print("      ")
        print("AKASH BERA")
        operator = int(input("(1).Details "))
        if operator == 1:
             print("      ")
             print("Your date of birth - 13/08/2006")
             print("      ")
             print("Your subjects is [English, Bengali, Physics, Chemistry, Math, Biology]")
             print("      ")
             print("You are now class 12")
             print("      ")
             print("Your roll is 22")
             print("      ")
             print("      ")
             print("      ")
             print("Your pin code is 711412")
             print(" ")
             print("Address - Kanupat,uatter/north bera para")
             print("      ")
             print("Your village - KANUPAT")
             print("      ")
             print("Your post - KANUPAT")
             print("      ")
             print("Your P.S - UDAYNARAYANPUR")
             print("      ")
             print("Your district - HOWRAH")
             print(" ")
             print(" ")
             print("THANK YOU FOR USING OUR SERVICES")
             print(" ")
             print(" ")
             print(" ")
             print(" ")
             print(" ")
             print(" ")
        else:
             print("invalid")
elif in_user_name == An_user_name or An_user_name + " " and in_password == An_password:
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("Log in into guest ankur")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("Welcome ANKUR you are in our program ")
        print("      ")
        print("ANKUR BERA")
        operator = int(input("(1).Details "))
        if operator == 1:
             print("      ")
             print("Your date of birth - 24/06/2006")
             print("      ")
             print("Your subjects is [English, Bengali, Physics, Chemistry, Math, Biology]")
             print("      ")
             print("You are now class 12")
             print("      ")
             print("Your roll is 23")
             print("      ")
             print("      ")
             print("      ")
             print("Your pin code is 711412")
             print(" ")
             print("Address - ")
             print("      ")
             print("Your village - ")
             print("      ")
             print("Your post - KANUPAT")
             print("      ")
             print("Your P.S - UDAYNARAYANPUR")
             print("      ")
             print("Your district - HOWRAH")
             print(" ")
             print(" ")
             print("THANK YOU FOR USING OUR SERVICES")
             print(" ")
             print(" ")
             print(" ")
             print(" ")
             print(" ")
             print(" ")
        else:
             print("invalid")

elif in_user_name == Z_user_name or Z_user_name + " " and in_password == Z_user_name:
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("Log in into guest ZISAN")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("      ")
        print("Welcome ZISAN you are in our program ")
        print("      ")
        print("SK ZISAN ALI")
        operator = int(input("(1).Details "))
        if operator == 1:
             print("      ")
             print("Your date of birth - 09/08/2006")
             print("      ")
             print("Your subjects is [English, Bengali, Physics, Chemistry, Math, Biology]")
             print("      ")
             print("You are now class 12")
             print("      ")
             print("Your roll is 9")
             print("      ")
             print("      ")
             print("      ")
             print("Your pin code is 711412")
             print(" ")
             print("Address - Purpat,Kanupat,Howrah")
             print("      ")
             print("Your village - PURPAT")
             print("      ")
             print("Your post - KANUPAT")
             print("      ")
             print("Your P.S - UDAYNARAYANPUR")
             print("      ")
             print("Your district - HOWRAH")
             print(" ")
             print(" ")
             print("THANK YOU FOR USING OUR SERVICES")
             print(" ")
             print(" ")
             print(" ")
             print(" ")
             print(" ")
             print(" ")
else:
    print("sorry " + in_user_name + " you are not in our program ")
print("THIS PROJECT IS CREATED BY SK SAHIL UDDIN ")
